# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: pod-status-service-account
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: {{ .Release.Namespace }}
#   name: pod-status-role
# rules:
# - apiGroups: [""]
#   resources: ["pods", "configmaps"]
#   verbs: ["get", "list"]
# - apiGroups: [""]
#   resources: ["configmaps"]
#   resourceNames: ["pod-status"]
#   verbs: ["patch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: pod-status-rolebinding
#   namespace: {{ .Release.Namespace }}
# subjects:
# - kind: ServiceAccount
#   name: pod-status-service-account
#   namespace: {{ .Release.Namespace }}
# roleRef:
#   kind: Role
#   name: pod-status-role
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: pod-status
#   namespace: {{ .Release.Namespace }}
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-status-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-status
  template:
    metadata:
      labels:
        app: pod-status
    spec:
      serviceAccountName: pod-status-service-account
      containers:
      - name: kubectl-container
        image: localhost:5000/kubectl:test
        env:
          - name: APK_RELEASE_NAME
            value: apk-test
          - name: APK_RESOURCE_PREFIX
            value: apk-test-wso2-apk
          - name: APK_RELEASE_NAMESPACE
            value: default

