apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-containeir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-containeir
  template:
    metadata:
      labels:
        app: kubectl-containeir
    spec:
      containers:
      # - name: write-to-postgresql
      #   image: localhost:5000/write-to-postgresql:3.0.0
      - name: kubectl-containeir
        image: localhost:5000/kubectl:34.0.0  # Use an image with kubectl installed
        volumeMounts:
          - name: logs
            mountPath: /app
      volumes:
        - name: logs
          emptyDir: {}
